--Basic	
require('core.plugins')
require('core.mappings')
require('core.colors')
require('core.configs')
--Plugs
require('plugins.lsp')
require('plugins.neotree')
require('plugins.treesitter')
require('plugins.telescope')
require('plugins.cmp')
require('plugins.mason')
